# Generated by Django 5.0.4 on 2024-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(max_length=100)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Ad', models.CharField(max_length=200)),
                ('Soyad', models.CharField(max_length=200)),
                ('Mail', models.EmailField(max_length=254)),
                ('GsmNo', models.CharField(max_length=15)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ihas',
            fields=[
                ('Iha_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Marka', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Agirlik', models.FloatField()),
                ('Kategori', models.CharField(max_length=100)),
                ('Kanat_w', models.FloatField()),
                ('Adet', models.IntegerField()),
                ('Musaitlik', models.BooleanField(default=True)),
                ('Bakim_yapildi_mi', models.BooleanField(default=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
