# Generated by Django 5.0.4 on 2024-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Sifre',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
