# Generated by Django 5.0.4 on 2024-05-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_sifre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='Iha_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
