# Generated by Django 5.0.4 on 2024-05-04 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihas',
            name='Musaitlik',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kira_baslangic', models.DateTimeField(default=django.utils.timezone.now)),
                ('kira_bitis', models.DateTimeField(blank=True, null=True)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('Iha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.ihas')),
            ],
        ),
    ]
