# Generated by Django 5.0.4 on 2024-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_ihas_musaitlik_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
